blank_issues_enabled: false
contact_links:
  - name: ğŸ“ â€‹ â€‹Typo or Grammatical Mistake
    url: https://github.com/thedaviddias/Resources-Front-End-Beginner/tree/main
    about: Please submit a pull request instead of reporting it as an issue.
